services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      # Persistent data storage for PostgreSQL
      - postgres_data:/var/lib/postgresql/data
      # Initialization scripts
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
    networks:
      - navable

networks:
  navable:
    driver: bridge

volumes:
  postgres_data:
    driver: local