name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd navable-api
          mvn clean package

      - name: Run tests
        run: |
          cd navable-api
          mvn test

      - name: Code Quality Check
        run: |
          cd navable-api
          mvn verify

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: navable-api/target/*.jar

  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: |
          cd navable
          flutter pub get

      - name: Run tests
        run: |
          cd navable
          flutter test

      - name: Analyze code quality
        run: |
          cd navable
          flutter analyze

      - name: Build release APK
        run: |
          cd navable
          flutter build apk --release

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: navable/build/app/outputs/flutter-apk/app-release.apk
